parameters:
- name: SkipTests
  displayName: Skip Tests
  type: boolean
  default: false

# CI and PR triggers
trigger:
- main
- feature/*
- release/*
pr:
- main
- feature/*
- release/*

resources:
  repositories:
  # Repo: 1ESPipelineTemplates/1ESPipelineTemplates
  - repository: 1esPipelines
    type: git
    name: 1ESPipelineTemplates/1ESPipelineTemplates
    ref: refs/tags/release
 
variables:
  - name: _TeamName
    value: DotNetTry
  - name: _BuildConfig
    value: Release
  - name: ArtifactsDirectory
    value: $(Build.SourcesDirectory)/artifacts
  - name: _PublishUsingPipelines
    value: true
  - name: _DotNetArtifactsCategory
    value: .NETCore
  - name: DotNetSdkVersion
    value: '8.0.101'
  - name: NodeJSVersion
    value: '16.13.0'
  - name: TryDotNetPackagesPath
    value: $(ArtifactsDirectory)/.trydotnet/packages
  - name: RunIntegrationTests
    value: true
  - name: Codeql.Enabled
    value: true

extends:
  # The pipeline extends the 1ES PT which will inject different SDL and compliance tasks.
  # For non-production pipelines, use "Unofficial" as defined below.
  # For productions pipelines, use "Official".
  template: v1/1ES.Official.PipelineTemplate.yml@1esPipelines
  parameters:
    # Update the pool with your team's 1ES hosted pool.
    pool:
      name: $(AzurePipelinePoolName)
      image: $(WindowsPipeLineImageName)
      os: windows
 
    # Build Tags
    customBuildTags:
    - TryDotNet
    - $(Build.BuildNumber)
 
    stages:
    - stage: build
      displayName: Build and Test
      jobs:
      - template: /eng/pipelines/templates/jobs/build.yml
        parameters:
          jobName: windows_nt
          displayName: Build/Test Windows
          poolOs: windows
          poolName: AzurePipelines-EO
          imageName: 1ESPT-Windows2022
      
      - template: /eng/pipelines/templates/jobs/build.yml
          parameters:
            jobName: linux
            displayName: Build/Test Linux
            poolOs: linux
            poolName: AzurePipelines-EO
            imageName: 1ESPT-Mariner2.0
